name-template: "Version $NEXT_PATCH_VERSION"
tag-template: "v$NEXT_PATCH_VERSION"
categories:
  - title: "New Features"
    labels:
      - feature
      - enhancement
  - title: "Bug Fixes"
    labels:
      - fix
      - bug
  - title: "Maintenance"
    labels:
      - chore
      - refactor
change-template: "- $TITLE (#$NUMBER)"
template: |
  ## Changes in this release

  $CHANGES

  _Generated automatically by GitHub Actions_
